config/routes.rb
RottenTomatoes::Application.routes.draw do
  
  resources :movies do 
    resources :reviews
  end
  
  resources :users, only: [:show, :new, :create]
  
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users
  end

  root to: 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  validates :title, presence: true
  validates :director,presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }
  validates :description, presence: true
  #validates :poster_image_url, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_past

  scope :with_title, -> (title) { where("title LIKE ?", "%#{title}%") }
  scope :with_director, -> (director) { where("director like ?", "%#{director}%") }
  scope :under_x_min, -> (max_limit) { where("runtime_in_minutes < ?", max_limit) }
  scope :over_x_min, -> (min_limit) { where("runtime_in_minutes >= ?", min_limit) }
  scope :with_title_or_director, -> (term) { where("title LIKE ? OR director LIKE ?", "%#{term}%", "%#{term}%") }

  mount_uploader :avatar, AvatarUploader

  def review_average
    if reviews.size > 0
      reviews.sum(:rating_out_of_ten)/reviews.size
    else 
      reviews.sum(:rating_out_of_ten)
    end
  end

  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "should be in the past") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: { only_integer: true }
  validates :rating_out_of_ten, numericality: { greater_than_or_equal_to: 1 }
  validates :rating_out_of_ten, numericality: { less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  validates :email, presence: true
  validates :email, uniqueness: true
  has_secure_password

  def full_name
    "#{firstname} #{lastname}"
  end

end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ActionController::Base

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_access

  def index
    @users = User.order(:firstname).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to admin_users_path
      else
        render :new
      end
  end

  def show 
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
      UserMailer.goodbye_email(@user).deliver
      flash[:success] = "User deleted"
      @user.destroy
      redirect_to admin_users_path
  end

  protected

  def restrict_access
    if !admin? 
      flash[:alert] = "You must be an admin to view!"
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 
  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def admin?  
    current_user.try(:admin?)
  end

  
   helper_method :current_user, :admin?
end
  

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
    @movies = @movies.with_title_or_director(params[:term]) if params[:term].present?
    @movies = @movies.with_title(params[:title]) if params[:title].present?
    @movies = @movies.with_director(params[:director]) if params[:director].present?
    @movies = @movies.under_x_min(90) if params[:duration] == "2"
    @movies = @movies.over_x_min(90).under_x_min(120) if params[:duration] == "3"
    @movies = @movies.over_x_min(120) if params[:duration] == "4"
  end


  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie=Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
  @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :avatar)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  
  before_filter :load_movie
  before_filter :restrict_access
  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end


  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

protected

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    user=User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to movies_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, {avatars: []})
  end


end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], url: admin_user_path do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "Email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "Admin?" %><br>
    <%= f.check_box :admin %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>
</form>

app/views/admin/users/edit.html.erb
<%= link_to "back to list", admin_users_path(@user) %>
<h2>Edit this user</h2>
<%= render 'form' %>   

app/views/admin/users/index.html.erb
<h1> Welcome to the Admin Page</h1>
<p><%= link_to "Create new user here!",new_admin_user_path %>
<hr>
<%= paginate @users %>
<% @users.each do |user| %>
  <li><h3><%= user.full_name %></h3>
    <p><% if user.admin? %>(admin) <% else %>(regular)</p><% end %>
    <p><%= user.email%></p>
    <%= button_to "Delete", admin_user_path(user.id), :method => :delete %>
    <p><%= link_to "edit user", edit_admin_user_path(user) %></p>
  </li>
<% end %>
<hr>
<%= link_to "Back to movie page", movies_path %> 
<hr>

app/views/admin/users/new.html.erb
<h2>Create New User</h2>

  <%= form_for @user, url: admin_users_path do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label "email" %><br>
    <%= f.text_field "email" %>
  </div>
  <div>
    <%= f.label "firstname", "First Name" %><br>
    <%= f.text_field "firstname" %>
  </div>
  <div>
    <%= f.label "lastname", "Last Name" %><br>
    <%= f.text_field "lastname" %>
  </div>
  <div>
    <%= f.label "password" %><br>
    <%= f.password_field "password" %>
  </div>
  <div>
    <%= f.label "password_confirmation" %><br>
    <%= f.password_field "password_confirmation" %>
  </div>
  <div>
    <%= f.label "Admin?" %><br>
    <%= f.check_box :admin %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>
</form>

app/views/admin/users/show.html.erb
<h1>Hollo World </h1>

<h4>Email: <%= @user.email%> (
 <% if current_user.admin? %>
 <%= link_to "Edit", edit_admin_user_path%>
 <% end %>, <%= link_to "Delete", admin_user_path(@user), method: :delete, data: {confirm: "You sure?"} %>)
</h4>

<h4>First name: <%= @user.firstname%></h4>
<h4>Last name: <%= @user.lastname%></h4>

<h4>Created on: <%= @user.created_at.in_time_zone("Pacific Time (US & Canada)").strftime("%B %d, %Y") %></h4>

app/views/layouts/_footer.html.erb
 <span class = "log_in">
    <% if current_user && current_user.admin? == false%>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% elsif current_user && current_user.admin? %>
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>) | <%= link_to "Admin Interface", admin_users_path %>
    <% else %>
      <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
 </span>

app/views/layouts/_search_form.html.erb
<%= form_tag("/movies", method: "get") do %>
<div class = "search-bar">
  <p>
    <%= label_tag(:term, "Search:") %>
    <%= text_field_tag(:term, nil, class: "searchfieldclass",:placeholder =>"by title or director") %>
      <%= label_tag(:duration, "Search by duration:") %>
    </span>
    <span class= "select">
    <%= select_tag(:duration, options_for_select([['All', 1], ['Under 90 minutes', 2], ['Between 90 and 120 minutes', 3], ['Over 120 minutes', 4]])) %>
    </span>
  </p>
</div>
  <div class = "search-button">
    <%= submit_tag("Search", class: "button is-primary") %>
  </div>
 

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottenTomatoes</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
  <body>
  <nav class="nav">
  <div class="nav-left">
    <a class="nav-item" href="#">
      <img src="http://png.clipart.me/graphics/thumbs/183/mango-polygonal-style-creative-vector-illustration_183470912.jpg" alt="Bulma logo}" height="42" width="42">
      <h3>ROTTEN MANGOS</h3>
    </a>
    <p class= 'submit-movie'><%= link_to "Submit a movie HERE!", new_movie_path, class: "button is-primary is-outlined" %></p>
    <div class="nav-center">
          <%= render 'layouts/search_form' %>
    </div>
    <div class = "nav-item">
      <div class = "Log_in">
      <%= render 'layouts/footer' %>
      </div>
    </div>

  </div>
  </nav>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value) %>
    <% end %>
    <%= yield %>

    
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: {multipart:true} do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "formfield-stuff">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "input" %>
  </div>
  <div class = "formfield-stuff">
    <%= f.label :release_date %><br>
    <%= f.date_field :release_date %>
  </div>
  <div class = "formfield-stuff">
    <%= f.label :director %><br>
    <%= f.text_field :director, class: "input" %>
  </div>
  <div class = "formfield-stuff">
    <%= f.label :runtime_in_minutes %><br>
    <%= f.number_field :runtime_in_minutes, class: "input" %>
  </div>
<!--   <div>
    <%= f.label :poster_image_url %><br>
    <%= f.text_field :poster_image_url %>
  </div> -->
   <div class = "formfield-stuff">
    <%= f.label :avatar %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class = "formfield-stuff">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "textarea" %>
  </div>
  <div class = "formfield-stuff">
    <%= f.submit "Submit", class: "button is-primary" %> 
  </div>
<% end %>

app/views/movies/_movie.html.erb
<% @movies.each do |movie| %>
<div class= "movieposition">
  <div class="card">
    <div class="card-image">
       <%= link_to(image_tag(movie.avatar, height: '210', width:'300'), movie_path(movie)) %>
    </div>
    <h2><%=link_to movie.title, movie_path(movie) %></h2>
    <h3><%= formatted_date(movie.release_date) %></h3>
    <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %>minutes</h4>
    <p><%= movie.description %></p>
    <p><%= movie.review_average %>/10</p>
  </div>
</div>  
<% end %>



<!-- <div class="card">
  <div class="card-image">
    <figure class="image is-4by3">
      <img src="http://placehold.it/300x225" alt="">
    </figure>
  </div>
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <figure class="image is-32x32">
          <img src="http://placehold.it/64x64" alt="Image">
        </figure>
      </div>
      <div class="media-content">
        <p class="title is-5">John Smith</p>
        <p class="subtitle is-6">@johnsmith</p>
      </div>
    </div>

    <div class="content">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Phasellus nec iaculis mauris. <a href="#">@bulmaio</a>.
      <a href="#">#css</a> <a href="#">#responsive</a>
      <br>
      <small>11:09 PM - 1 Jan 2016</small>
    </div>
  </div>
</div> -->

app/views/movies/edit.html.erb
<%= link_to "Back to this movie", movie_path(@movie) %>
<h2>Edit this movie.</h2>
<%= render 'form' %>    

app/views/movies/index.html.erb
<%= render 'movie' %>

app/views/movies/new.html.erb
<%= link_to "Back to all movies", movies_path %>
<h2>Submit a movie!</h2>
<%= render 'form' %>   

app/views/movies/show.html.erb
<%= link_to "Back to all movies", movies_path %><br/>
<hr>

        <%= link_to image_tag(@movie.avatar, height: '320', width: '540'), movie_path(@movie) %>
      <h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
      <h3><%= formatted_date(@movie.release_date)%></h3>
      <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
      <p><%= @movie.description %></p>

      <hr>

      <h3>Reviews of <em><%= @movie.title %></em></h3>
      <% if current_user %>
        <% @movie.reviews.each do |review| %>
          <p><%= review.text %></p>
          <p><%= review.rating_out_of_ten %>/10</p>
          <small>- <%= review.user.full_name %></small><br/>
        <% end %>
        <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
      <% else %>
        <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 

<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
 <%= link_to "Back to movie", movie_path(@movie) %><br/>

    <h2>Write a review of <em><%= @movie.title %></em>.</h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area "text" %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div>
        <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
  <% end %>
    <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
  <h3>First name: <%= @user.firstname %></h3>
  <h3>Last name: <%= @user.lastname %></h3>
  <h3>Email: <%= @user.email %></h3>